const Types = {
  ADD_COURSE_REQUEST: 'COURSE/ADD_COURSE_REQUEST',
  ADD_SUCCESS: 'COURSE/ADD_COURSE_SUCCESS',
  ADD_FAILURE: 'COURSE/ADD_COURSE_FAILURE',
  ADD_ONCHANGE: "COURSE/ONCHANGE_ADD",
  ADD_CHANGE_STEP: "COURSE/ADD_CHANGE_STEP",
  VIEW_CHOOSE_ITEMS: 'COURSE/VIEW_STUDENT_CHOOSE_ITEMS',
  ADD_CHECK_INFO: 'COURSE/ADD_COURSE_CHECK_INFO_DATA',
  ADD_CHECK_INFO_SUCCESS: 'COURSE/ADD_COURSE_CHECK_INFO_SUCCESS',
  ADD_CHECK_INFO_FAILURE: 'COURSE/ADD_COURSE_CHECK_INFO_FAILURE',
  ADD_CHECK_INFO_CHANGE_STATE: 'COURSE/ADD_COURSE_CHECK_INFO_CHANGE_STATE',
  INIT: "COURSE/GET_ACTION",
  INIT_SUCCESS: "COURSE/GET_ACTION_SUCCESS",
  RESET: "COURSE/RESET",
};

export default Types;
