const Types = {
  CONTENT_GET_CONTENT: "CONTENT/GET_COURSE_CONTENT",
  CONTENT_GET_SUCCESS: "CONTENT/GET_COURSE_SUCCESS",
  CONTENT_GET_FAILURE: "CONTENT/GET_COURSE_FAILURE",
  RESET: "CONTENT/RESET",
  CONTENT_ONCHANGE: "CONTENT/ONCHANGE_CONTENT",
  CONTENT_ADD_REQUEST: "CONTENT/ADD_CONTENT_REQUEST",
  ADD_CONTENT_SUCCESS: "CONTENT/ADD_CONTENT_SUCCESS",
  ADD_CONTENT_FAILURE: "CONTENT/ADD_CONTENT_FAILURE",
  MODAL_OPEN_CONTENT: "CONTENT/MODAL_OPEN_STATE",
  MODAL_CLOSE_CONTENT: "CONTENT/MODAL_CLOSE_STATE",
  DELETE_CONTENT:"CONTENT/DELETE_CONTENT",
  DELETE_CONTENT_SUCCESS:"CONTENT/DELETE_CONTENT_SUCCESS",
  DELETE_CONTENT_ERROR:"CONTENT/DELETE_CONTENT_FAILURE",
  CONTENT_DIALOG_CLOSE:'CONTENT/CONTENT_DIALOG_CLOSE',
  CONTENT_DIALOG_OPEN:'CONTENT/CONTENT_DIALOG_OPEN',
};

export default Types;
