const Types = {
  ONCHANGE: "REGISTER_STUDENT/ONCHANGE",
  SUBMIT_ADD_STUDENT: "REGISTER_STUDENT/SUBMIT_ADD_STUDENT",
  SUBMIT_ADD_STUDENT_DONE: "REGISTER_STUDENT/SUBMIT_ADD_STUDENT_DONE",
  SUBMIT_ADD_STUDENT_ERROR: "REGISTER_STUDENT/SUBMIT_ADD_STUDENT_ERROR",
  RESET: "REGISTER_STUDENT/RESET",
  INIT: "REGISTER_STUDENT/INTI",
  INIT_DONE: "REGISTER_STUDENT/INTI_DONE",
  UPDATE_PASSWORD: "REGISTER_STUDENT/UPDATE_PASSWORD",
  UPDATE_PASSWORD_DONE: "REGISTER_STUDENT/UPDATE_PASSWORD_DONE",
  UPDATE_STUDENT: "REGISTER_STUDENT/UPDATE_STUDENT",
  UPDATE_STUDENT_DONE: "REGISTER_STUDENT/UPDATE_STUDENT_DONE",
};

export default Types;
