const Types = {
  RESET: "ADMIN_DASHBOARD/RESET",
  INIT: "ADMIN_DASHBOARD/INIT",
  INIT_DONE: "ADMIN_DASHBOARD/INIT_DONE",
  ONCHANGE_DASHBOARD: "ADMIN_DASHBOARD/ONCHANGE_DASHBOARD",
  GET_RESULT_DASHBOARD: "ADMIN_DASHBOARD/GET_RESULT_DASHBOARD",
  GET_RESULT_DASHBOARD_DONE: "ADMIN_DASHBOARD/GET_RESULT_DASHBOARD_DONE",
  VIEW_CHANGE_PAGE: "ADMIN_DASHBOARD/VIEW_CHANGE_PAGE",
  VIEW_CHANGE_ROW: "ADMIN_DASHBOARD/VIEW_CHANGE_ROW",
  REMOVEW_DATA: 'ADMIN_DASHBOARD/RESTORE_DATA',
  REMOVEW_DATA_SUCCESS: 'ADMIN_DASHBOARD/RESTORE_DATA_SUCCESS',
  VIEW_DIALOG_CLOSE:'ADMIN_DASHBOARD/VIEW_EXAM_DIALOG_CLOSE',
  VIEW_DIALOG_OPEN:'ADMIN_DASHBOARD/VIEW_EXAM_DIALOG_OPEN',
};

export default Types;
