const Types = {
  RESET: "STUDENT_DO_TEST/RESET",
  INIT: "STUDENT_DO_TEST/INIT",
  INIT_DONE: "STUDENT_DO_TEST/INIT_DONE",
  INIT_FAILURE: "STUDENT_DO_TEST/INIT_FAILURE",
  DO_TEST_ONCHANGE: "STUDENT_DO_TEST/ONCHANGE_DO_TEST_ONCHANGE",
  DO_TEST_DONE:"STUDENT_DO_TEST/_DO_TEST_DONE",
};

export default Types;
