const Types = {
  ADD_ONCHANGE: "EXAM/ONCHANGE_ADD",
  ADD_CHANGE_STEP: "EXAM/ADD_CHANGE_STEP",
  ADD_EXAM: 'EXAM/ADD_EXAM_CHECK_INFO_DATA',
  ADD_EXAM_SUCCESS: 'EXAM/ADD_EXAM_SUCCESS',
  ADD_EXAM_FAILURE: 'EXAM/ADD_EXAM_FAILURE',
  ADD_EXAM_CHANGE_STATE: 'EXAM/ADD_EXAM_CHANGE_STATE',
  INIT: "EXAM/GET_ACTION",
  INIT_SUCCESS: "EXAM/GET_ACTION_SUCCESS",
  RESET: "EXAM/RESET",
  ADD_EXAM_REQUEST: 'EXAM/ADD_EXAM_REQUEST',
};

export default Types;
