const Types = {
  RESET: "STUDENT_TEST/RESET",
  INIT: "STUDENT_TEST/INIT",
  INIT_DONE: "STUDENT_TEST/INIT_DONE",
  INIT_DONE_RESULT: "STUDENT_TEST/INIT_DONE_RESULT",
  INIT_FAILURE: "STUDENT_TEST/INIT_FAILURE",
  OPEN_TEST: "STUDENT_TEST/DO_TEST",
  OPEN_TEST_RESUME: "STUDENT_TEST/DO_TEST_RESUME",
  ONCHANGE: "STUDENT_TEST/ONCHANGE_PAGE",
};

export default Types;
