const Types = {
  GET_PROFILE: "STUDENT/DASHBOARD/GET_PROFILE",
  INIT: "STUDENT/DASHBOARD/INIT",
  INIT_DONE: "STUDENT/DASHBOARD/INIT_DONE",
  SWITCH_MENU: "STUDENT/DASHBOARD/MENU",
};
export default Types;
