const Types = {
  RESET: "STUDENT_DASHBOARD/RESET",
  INIT: "STUDENT_DASHBOARD/INIT",
  INIT_DONE: "STUDENT_DASHBOARD/INIT_DONE",
  DETAIL_COURSE: "STUDENT_DASHBOARD/OPEN_COURSE",
};

export default Types;
