const Types = {
  RESET: "STUDENT_COURSE/RESET",
  INIT: "STUDENT_COURSE/INIT",
  INIT_DONE: "STUDENT_COURSE/INIT_DONE",
  INIT_FAILURE: "STUDENT_COURSE/INIT_FAILURE",
  OPEN_TEST: "STUDENT_COURSE/OPEN_TEST",
};

export default Types;
