const Types = {
    VIEW_COURSE_REQUEST: "LIST@@STUDENT/VIEW_STUDENT_REQUEST",
    VIEW_SUCCESS: "LIST@@STUDENT/VIEW_STUDENT_SUCCESS",
    VIEW_FAILURE: "LIST@@STUDENT/VIEW_STUDENT_FAILURE",
    VIEW_CHANGE_PAGE: "LIST@@STUDENT/VIEW_STUDENT_CHANGE_PAGE",
    VIEW_CHANGE_ROW: "LIST@@STUDENT/VIEW_STUDENT_CHANGE_ROW",
    VIEW_CHOOSE_ITEMS: "LIST@@STUDENT/VIEW_STUDENT_CHOOSE_ITEMS",
    VIEW_DELETE_ITEMS: "LIST@@STUDENT/VIEW_STUDENT_DELETE_ITEMS",
    VIEW_DELETE_SUCCESS: "LIST@@STUDENT/VIEW_STUDENT_DELETE_SUCCESS",
    VIEW_DELETE_FAILURE: "LIST@@STUDENT/VIEW_STUDENT_DELETE_FAILURE",
    VIEW_SEARCH_TEXT: "LIST@@STUDENT/VIEW_STUDENT_SEARCH_TEXT",
    VIEW_SELECT_ROW: "LIST@@STUDENT/VIEW_STUDENT_SELECT_ROW",
    RESET: "LIST@@STUDENT/VIEW_RESET",
    VIEW_DIALOG_CLOSE: 'LIST@@STUDENT/VIEW_COURSE_DIALOG_CLOSE',
    VIEW_DIALOG_OPEN: 'LIST@@STUDENT/VIEW_COURSE_DIALOG_OPEN',
    VIEW_ONCHANGE: "LIST@@STUDENT/ONCHANGE_VIEW",
    DOWNLOAD_FILE: "LIST@@STUDENT/DOWNLOAD_FILE",
    DOWNLOAD_FILE_DONE: "LIST@@STUDENT/DOWNLOAD_FILE_DONE",
};

export default Types;
