const Types = {
  VIEW_STUDENT_REQUEST: 'COURSE/@@STEP1/VIEW_COURSE_REQUEST',
  VIEW_SUCCESS: 'COURSE/@@STEP1/VIEW_COURSE_SUCCESS',
  VIEW_FAILURE: 'COURSE/@@STEP1/VIEW_COURSE_FAILURE',
  VIEW_CHANGE_PAGE: 'COURSE/@@STEP1/VIEW_COURSE_CHANGE_PAGE',
  VIEW_CHANGE_ROW: 'COURSE/@@STEP1/VIEW_COURSE_CHANGE_ROW',
  // VIEW_CHOOSE_ITEMS: 'COURSE/@@STEP1/VIEW_COURSE_CHOOSE_ITEMS',
  VIEW_GET_SELECTED:'COURSE/@@STEP1/VIEW_GET_SELECTED',
  VIEW_SEARCH_TEXT: 'COURSE/@@STEP1/VIEW_COURSE_SEARCH_TEXT',
  VIEW_ONCHANGE: "COURSE/@@STEP1/ONCHANGE_VIEW",
};

export default Types;
