const Types = {
  RESET: "STUDENT_RESULT_EXAM/RESET",
  INIT: "STUDENT_RESULT_EXAM/INIT",
  INIT_DONE: "STUDENT_RESULT_EXAM/INIT_DONE",
  VIEW_CHANGE_PAGE: "STUDENT_RESULT_EXAM/VIEW_CHANGE_PAGE",
  VIEW_CHANGE_ROW: "STUDENT_RESULT_EXAM/VIEW_CHANGE_ROW",
};

export default Types;
