const Types = {
  ADD_ONCHANGE: "QUIZ/ONCHANGE_ADD",
  EXAM_GET_QUIZ: "QUIZ/GET_EXAM_QUIZ",
  QUIZ_GET_SUCCESS: "QUIZ/GET_QUIZ_SUCCESS",
  QUIZ_GET_FAILURE: "QUIZ/GET_QUIZ_FAILURE",
  RESET: "QUIZ/RESET",
  MODAL_OPEN_QUIZ:"QUIZ/CLICK_OPEN_QUIZ",
  MODAL_CLOSE_QUIZ:"QUIZ/CLICK_CLOSE_QUIZ",
  QUIZ_ADD_REQUEST: "QUIZ/ADD_QUIZ_REQUEST",
  ADD_QUIZ_SUCCESS: "QUIZ/ADD_QUIZ_SUCCESS",
  ADD_QUIZ_FAILURE: "QUIZ/ADD_QUIZ_FAILURE",
  DELETE_QUIZ:"QUIZ/DELETE_QUIZ",
  DELETE_QUIZ_SUCCESS:"QUIZ/DELETE_QUIZ_SUCCESS",
  DELETE_QUIZ_ERROR:"QUIZ/DELETE_QUIZ_FAILURE",
  QUIZ_DIALOG_CLOSE:'QUIZ/QUIZ_DIALOG_CLOSE',
  QUIZ_DIALOG_OPEN:'QUIZ/QUIZ_DIALOG_OPEN',
};

export default Types;
