const Types = {
  VIEW_EXAM_REQUEST: 'EXAM/VIEW_EXAM_REQUEST',
  VIEW_SUCCESS: 'EXAM/VIEW_EXAM_SUCCESS',
  VIEW_FAILURE: 'EXAM/VIEW_EXAM_FAILURE',
  VIEW_CHANGE_PAGE: 'EXAM/VIEW_EXAM_CHANGE_PAGE',
  VIEW_CHANGE_ROW: 'EXAM/VIEW_EXAM_CHANGE_ROW',
  VIEW_CHOOSE_ITEMS: 'EXAM/VIEW_EXAM_CHOOSE_ITEMS',
  VIEW_DELETE_ITEMS: 'EXAM/VIEW_EXAM_DELETE_ITEMS',
  VIEW_DELETE_SUCCESS: 'EXAM/VIEW_EXAM_DELETE_SUCCESS',
  VIEW_DELETE_FAILURE: 'EXAM/VIEW_EXAM_DELETE_FAILURE',
  VIEW_SEARCH_TEXT: 'EXAM/VIEW_EXAM_SEARCH_TEXT',
  VIEW_SELECT_EDIT: 'EXAM/VIEW_EXAM_SELECT_EDIT',
  VIEW_SELECT_ROW: 'EXAM/VIEW_EXAM_SELECT_ROW',
  RESET: "EXAM/VIEW_RESET",
  VIEW_DIALOG_CLOSE:'EXAM/VIEW_EXAM_DIALOG_CLOSE',
  VIEW_DIALOG_OPEN:'EXAM/VIEW_EXAM_DIALOG_OPEN',
  VIEW_ONCHANGE: "EXAM/ONCHANGE_VIEW",
};

export default Types;
