const Types = {
  ONCHANGE: "ADD_STUDENT/ONCHANGE",
  SUBMIT_ADD_STUDENT: "ADD_STUDENT/SUBMIT_ADD_STUDENT",
  SUBMIT_ADD_STUDENT_DONE: "ADD_STUDENT/SUBMIT_ADD_STUDENT_DONE",
  SUBMIT_ADD_STUDENT_ERROR: "ADD_STUDENT/SUBMIT_ADD_STUDENT_ERROR",
  RESET: "ADD_STUDENT/RESET",
  INIT: "ADD_STUDENT/INTI",
  INIT_DONE: "ADD_STUDENT/INTI_DONE",
  UPDATE_PASSWORD: "ADD_STUDENT/UPDATE_PASSWORD",
  UPDATE_PASSWORD_DONE: "ADD_STUDENT/UPDATE_PASSWORD_DONE",
  UPDATE_STUDENT: "ADD_STUDENT/UPDATE_STUDENT",
  UPDATE_STUDENT_DONE: "ADD_STUDENT/UPDATE_STUDENT_DONE",
};

export default Types;
