const Types = {
  LOGIN_REQUEST: 'LOGIN/USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN/USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN/USERS_LOGIN_FAILURE',
  UPDATE_LOADING_LOGIN: 'LOGIN/UPDATE_LOADING_LOGIN',

  LOGOUT: 'LOGIN/USERS_LOGOUT',
  SWITCH_PORTAL: 'LOGIN/SWITCH_PORTAL',
};

export default Types;
