const Types = {
  // LOGIN_REQUEST: 'LOGIN/USERS_LOGIN_REQUEST',
  ON_CHANGE: "USER/PROFILE/ON_CHANGE",
  UPDATE_PASSWORD: "USER/PROFILE/UPDATE_PASSWORD",
  CHANGE_PASS_SUCCESS: "USER/PROFILE/CHANGE_PASS_SUCCESS",
  CHANGE_PASS_ERRORS: "USER/PROFILE/CHANGE_PASS_ERRORS",
};

export default Types;
