const Types = {
  VIEW_COURSE_REQUEST: 'COURSE/VIEW_COURSE_REQUEST',
  VIEW_SUCCESS: 'COURSE/VIEW_COURSE_SUCCESS',
  VIEW_FAILURE: 'COURSE/VIEW_COURSE_FAILURE',
  VIEW_CHANGE_PAGE: 'COURSE/VIEW_COURSE_CHANGE_PAGE',
  VIEW_CHANGE_ROW: 'COURSE/VIEW_COURSE_CHANGE_ROW',
  VIEW_CHOOSE_ITEMS: 'COURSE/VIEW_COURSE_CHOOSE_ITEMS',
  VIEW_DELETE_ITEMS: 'COURSE/VIEW_COURSE_DELETE_ITEMS',
  VIEW_DELETE_SUCCESS: 'COURSE/VIEW_COURSE_DELETE_SUCCESS',
  VIEW_DELETE_FAILURE: 'COURSE/VIEW_COURSE_DELETE_FAILURE',
  VIEW_SEARCH_TEXT: 'COURSE/VIEW_COURSE_SEARCH_TEXT',
  VIEW_SELECT_EDIT: 'COURSE/VIEW_COURSE_SELECT_EDIT',
  VIEW_SELECT_DETAIL: 'COURSE/VIEW_COURSE_SELECT_DETAIL',
  VIEW_SELECT_ROW: 'COURSE/VIEW_COURSE_SELECT_ROW',
  RESET: "COURSE/VIEW_RESET",
  VIEW_DIALOG_CLOSE:'COURSE/VIEW_COURSE_DIALOG_CLOSE',
  VIEW_DIALOG_OPEN:'COURSE/VIEW_COURSE_DIALOG_OPEN',
  VIEW_ONCHANGE: "COURSE/ONCHANGE_VIEW",
};

export default Types;
